### ISSUE TITLE
Develop Maintainer onboarding process and curriculum

### ISSUE THREAD

**Issue by kariljordan** [carpentries/strategic-plan#10]
[Goal 4](https://github.com/carpentries/strategic-plan#goal-4-facilitate-the-creation-and-maintenance-of-relevant-high-quality-community-curated-curricula) of our strategic plan is to "Facilitate the creation and maintenance of relevant, high-quality, Community-curated curricula." One of the objectives under this goal is to "Develop a comprehensive Maintainer program including onboarding, mentorship, regular recruitment/retirement cycles, and accessible lesson infrastructure."

The specific scope of work to be done for this issue is to develop and document our process for onboarding Maintainers and to update our [Maintainer onboarding curriculum](https://carpentries.github.io/maintainer-onboarding/).

Before 2018, Maintainers did not receive any training or guidance in their role. In early 2018, we developed and piloted a Maintainer onboarding process to introduce new and existing Maintainers to the social, curricular, and technical aspects of being a Maintainer and onboarded 27 new Maintainers to our lessons using these materials. 

To continue to support onboarding of new Maintainers on an ongoing basis, we have brought on board a Maintainer Community Engagement Lead, Angela Li, an R Spatial Advocate at the Center for Spatial Data Science at University of Chicago, Illinois. Angela is an active member of The Carpentries community, serving as an Instructor, Maintainer, Instructor Trainer, and Mentor. She also has experience in community organization through her role as co-founder of the R-Ladies Chicago chapter. Since January, Angela has led efforts in building and sustaining the Maintainer community. She has rebooted our Maintainer Onboarding program, recruiting 33 new volunteer Maintainers from nine countries around the world. These new Maintainers will complete onboarding in July and become full-fledged members of the Maintainer team. In rebooting the Maintainer Onboarding program, Angela is evaluating our current structures for integrating new Maintainers into the team, as well as taking stock of future need for more Maintainer support. 

**To Do**
- [x] Publish updated Maintainer Onboarding curriculum
- [x] Certify newly onboarded Maintainers (July 2020)
- [x] Update documentation of onboarding process in The Carpentries Handbook

**Comment by ErinBecker** [comment]
Goal of "Certify newly onboarded Maintainers" has been met and [blog post announcing new Maintainers](https://carpentries.org/blog/2020/07/maintainer-welcome-2020/) is out!

**Comment by tobyhodges** [comment]
I think the updated Onboarding curriculum was published. @erinbecker can you confirm please?

**Comment by ErinBecker** [comment]
Angelia Li substantially updated the Maintainer Onboarding curriculum in June/July 2020, but it was never officially published on Zenodo. The [Maintainer Onboarding section in The Carpentries Handbook](https://docs.carpentries.org/topic_folders/maintainers/maintainers.html#maintainer-onboarding) still mentions using Google Groups, which means its at least 2 years out of date. 

Work on this item needs to continue in Year 2 of the Strategic Plan. I am removing the month markers in the original description of the issue and will work with the Curriculum Team to get this back on our team roadmap.

**Comment by ErinBecker** [comment]
Publication of the Maintainer onboarding curriculum is planned for early May, ahead of the next round of Maintainer recruitment and onboarding in June/July.

**Comment by ErinBecker** [comment]
Labelling as both Q2 and Q3 2021, as work will be finished in Q3 but a lot of the work will happen in Q2.

**Comment by ErinBecker** [comment]
The Maintainer Onboarding curriculum [was published](https://zenodo.org/record/5504403#.YVxcA0bMKv5) 13 September. Still remaining on this issue is updating the onboarding process in the handbook. Changing tag to Q4 to reflect that final item will be completed in this quarter.
