### ISSUE TITLE
Create Membership Onboarding 

### ISSUE THREAD

**Issue by kariljordan** [carpentries/strategic-plan#15]
We now have a [membership onboarding packet](https://docs.google.com/document/d/1UQA_bRrFVsjCHuosIz6IoT1RHclvuu3rGx1d2PUsKaU/edit) that is sent to new members with information about how to use their benefits. We have piloted a more involved membership onboarding for the 5 seed IMLS members which includes face-to-face meetings with the ED ([link to slide deck](https://docs.google.com/presentation/d/1wZ-ritTVf3nP8k5QoFda_nW9ADbELvrHrZ6JSY8OAlE/edit)). We haven't yet expanded this onboarding to include all new members, so we should continue this item into Q2.

**Comment by ErinBecker** [comment]
We now have a [membership onboarding packet](https://docs.google.com/document/d/1UQA_bRrFVsjCHuosIz6IoT1RHclvuu3rGx1d2PUsKaU/edit) that is sent to new members with information about how to use their benefits. We have piloted a more involved membership onboarding for the 5 seed IMLS members which includes face-to-face meetings with the ED ([link to slide deck](https://docs.google.com/presentation/d/1wZ-ritTVf3nP8k5QoFda_nW9ADbELvrHrZ6JSY8OAlE/edit)). We haven't yet expanded this onboarding to include all new members, so we should continue this item into Q2.

**Comment by kariljordan** [comment]
We now have a [membership onboarding packet](https://docs.google.com/document/d/1UQA_bRrFVsjCHuosIz6IoT1RHclvuu3rGx1d2PUsKaU/edit) that is sent to new members with information about how to use their benefits. We have piloted a more involved membership onboarding for the 5 seed IMLS members which includes face-to-face meetings with the ED ([link to slide deck](https://docs.google.com/presentation/d/1wZ-ritTVf3nP8k5QoFda_nW9ADbELvrHrZ6JSY8OAlE/edit)). We haven't yet expanded this onboarding to include all new members, so we will continue this item into Q2 and track progress in #48.
