### ISSUE TITLE
Document Lessons Learned from Hiring Internationally

### ISSUE THREAD

**Issue by kariljordan** [carpentries/strategic-plan#16]
[Goal 5](https://github.com/carpentries/strategic-plan/blob/master/README.md#goal-5-strengthen-organisational-structure-and-capacity-to-be-strategic-and-responsive) of our strategic plan is to "Strengthen organisational structure and capacity to be strategic and responsive."

Two of the objectives under this goal are:
- Develop fair and equitable human resource policies for Core Team members in collaboration with our fiscal sponsor.
- Establish workflow and documentation for our essential ongoing processes (e.g. budget creation and review, communication channel use), and identify areas for effective and appropriate automation or other improvements needed to scale support.

We have recently engaged some international team members through a professional employment organisation (PEO). The scope of this task is to document what we learned in the process of forming these engagements and to update our workflows and templates accordingly. 

This includes (but may not be limited to):
- [x] Updating our [hiring process workflow](https://docs.google.com/document/d/1N7EWJo-c2FwP66httOqXitoWbdXppyKkZV_ggiWRAkY/edit)
- [x] Updating our Asana template for new hires

**Comment by ErinBecker** [comment]
We have incorporated our experiences with international hiring and contracting into the internal hiring workflow and Asana template. We now have a process for determining feasibility of hiring in a new country, benchmarking salary for an individual in that country for a specific position (based in part on hiring costs and social taxes), and working with Community Initiatives and the PEO Velocity Global to hire. @kariljordan I believe this issue can be closed as complete!
