### ISSUE TITLE
Develop first set of modules to train Community Facilitators for The Carpentries

### ISSUE THREAD

**Issue by kariljordan** [carpentries/strategic-plan#20]
**<ins>Context</ins>**
In 2019, Kari Jordan, Tracy Teal, Sher! Hurt and Serah Rono constituted a working group that discussed supporting community members through conflict. From our working group's deliberations, we saw the need to set up a task force that would issue recommendations for dealing with incidents that come up in spaces where our community members are but whose review and resolution fall outside the mandate of The Carpentries Code of Conduct (CoC) committee.([See task force charter](https://github.com/carpentries/task-forces/blob/master/2019/incidents-outside-cocc/2019-07-incidents-outside-cocc-charter.md). 

[One of the key recommendations from this Task Force was the institution of a Code of Conduct Facilitators Program](https://github.com/carpentries/task-forces/blob/master/2019/incidents-outside-cocc/2019-09-19-cocc-taskforce-summary-recommendations.md#recommendation-2-volunteer-code-of-conduct-facilitators) to serve as an added layer of support for our community before incidents are reported to the Code of Conduct Committee (CoCc). Details in the Code of Conduct Facilitators Program were first proposed by Malvika Sharan in Q1 2019. In summary, while maintaining the role of the CoCc as a CoC enforcement body, Code of Conduct Facilitators would actively monitor our online spaces and physical meetings and share potentially negative behaviours or otherwise certify that the community is functioning as expected. 

The Carpentries is keen to expand on the original mandate of Code of Conduct Facilitators in The Carpentries beyond support for others in situations of conflict, and hope to include elements of encouragement and positive facilitation that are necessary for the health and continuance of an established community like The Carpentries as part of the mandate of community facilitators in The Carpentries. This, we believe, will help Facilitators feel more fulfilled in this role, and open up pathways for them to build trust with community members, a necessary aspect of this role. 

**<ins>Phases of the Community Facilitators Program</ins>**
Developing a first set of modules to train Community Facilitators for The Carpentries is the second of multiple phases toward the creation and launch of the Community Facilitators Program in The Carpentries. Other phases are: 

- Phase 1: https://github.com/carpentries/strategic-plan/issues/14
- Phase 3: https://github.com/carpentries/strategic-plan/issues/25
- Phase 4: https://github.com/carpentries/strategic-plan/issues/33

**<ins>Aims of the four-phase Community Facilitators Program</ins>**
- Develop a curriculum module to address recommendation 2 from Q3 2019’s Task Force work
- Train first cohort of Community Facilitators on Code of Conduct facilitation
- Pilot Code of Conduct facilitation
- Identify topics for additional modules for the Community Facilitators Program
- Invite community members to apply to be in the second cohort of the Community Facilitators Program
- Train second cohort of Community Facilitators
- Prepare second cohort of Community Facilitators for collaborative work in the first half of 2021
- Offboard first cohort of Community Facilitators

**<ins>Aims of the Community Facilitators Program</ins>**
- Change the existing Code of Conduct enforcement mechanism that The Carpentries has in place
- Redesign or replace The Carpentries Mentorship program
- Develop a curriculum and resources for local community building in The Carpentries
- Develop a framework for a communications committee

**<ins>Resources that will constitute the roadmap for the Community Facilitators Program (Phase 2 work)</ins>**
- [x] Determine aspects of the first phase to communicate about at different stages of the work
- [x] Develop and pilot the first set of modules of the Community facilitators Program

**Comment by serahrono** [comment]
We recently [announced the launch of our Community Facilitators Program](https://carpentries.org/blog/2020/09/introducing-community-facilitators-program/) in The Carpentries. This week will mark the end of the onboarding period for [our first cohort of community facilitators whose focus will be feedback facilitation](https://carpentries.org/blog/2020/09/apply-feedback-facilitators-cohort/) over the next six months. 

We have also [set up a GitHub repository to hold all resources in this program](https://github.com/carpentries/community-facilitators-program), and made [content on Feedback Facilitation in The Carpentries available](https://carpentries.github.io/community-facilitators-program/02-0-feedback-facilitation/index.html) to the public and to feedback facilitators for reference in their time on the cohort here.

**Comment by kariljordan** [comment]
So proud of this work! Thank you Serah.
