### ISSUE TITLE
Establish recurring cycles for Maintainer Recruitment and Retirement

### ISSUE THREAD

**Issue by kariljordan** [carpentries/strategic-plan#21]
[Goal 4](https://github.com/carpentries/strategic-plan#goal-4-facilitate-the-creation-and-maintenance-of-relevant-high-quality-community-curated-curricula) of our strategic plan is to "Facilitate the creation and maintenance of relevant, high-quality, Community-curated curricula." One of the objectives under this goal is to:

- Develop a comprehensive Maintainer program including onboarding, mentorship, regular recruitment/retirement cycles, and accessible lesson infrastructure.

The specific scope of this issue is to establish recurring cycles for Maintainer Recruitment and Retirement. After processes are developed for [Recruitment](#10) and retirement, we need to ensure that these processes are carried out routinely to provide new maintainers and to enable existing maintainers to step down from their duties as needed. 

Creating a retirement process for Maintainers, similar to our Trainer alumni program, will enable inactive Maintainers to step down without guilt and allow us to more accurately gauge the level of support we have on each of our lessons so that we can recruit new Maintainers efficiently.

**To Do**
- [x] Determine appropriate cycle lengths for recruitment and retirement.
- [x] Set up recurring tasks as needed to initiate these processes.

This issue is dependent on #10 and #17.

**Comment by ErinBecker** [comment]
We have an established process for Maintainer recruitment, including an Asana project template, template emails, an application form, and blog post templates. 

We do not yet have the same products for Maintainer retirement process, which is dependent on development of the Maintainer volunteer agreement, in discussion by Maintainers at [this RFC](https://github.com/carpentries/maintainer-RFCs/issues/15).

**Comment by ErinBecker** [comment]
No progress on development of a Maintainer retirement process. This quarter focused on onboarding new Maintainers and developing the CAC roles and responsibilities. Work on this issue will restart in Q4. Changing tag to reflect updated timeline.

**Comment by tobyhodges** [comment]
In Q4 we prepared the ground for a first step towards a retirement process for Maintainers: a single-question opt-in survey for Maintainers to tell us if they wish to remain active on their lesson. [This is the RFC for that process](https://github.com/carpentries/maintainer-RFCs/issues/19), which is currently ongoing.

**Comment by ErinBecker** [comment]
This work will be completed in Q2 2022 with the creation of templates and workflows for retirement and recruitment.

**Comment by ErinBecker** [comment]
We have completed the first round of Maintainer Retirement, which will happen yearly starting in January. [Template emails and a workflow](https://docs.google.com/document/d/14rFlc6-BSleBh--CXQvUkgQZJxxXjXAn_w6R0CpeJJc/) have been developed for retirement, and will be adapted / improved in future cycles. 

Maintainer recruitment and onboarding is underway and will occur at a minimum every year following retirement, with a possible second session each year depending on need. An [Asana template](https://app.asana.com/0/1185099340351503/list) for this process has been created and [recurring reminders](https://app.asana.com/0/1202390302041414/list) set up to initiate the process.
