### ISSUE TITLE
Instructor Training Curriculum Updates

### ISSUE THREAD

**Issue by kariljordan** [carpentries/strategic-plan#23]
The Instructor Training curriculum is a mechanism for meeting many of the goals in the Strategic Plan. It is the primary mode of [professional development](https://github.com/carpentries/strategic-plan#goal-3-provide-opportunities-for-growth-and-professional-development-of-our-volunteers-and-core-team) available to community volunteers. It is the sole source of instruction on community standards around [equity and inclusion](https://github.com/carpentries/strategic-plan#goal-2-intentionally-incorporate-equity-inclusion-and-accessibility-to-support-a-diverse-community) for most community-members. And, as we look to expand our curricular offerings, the content of this workshop itself is frequently requested as a [stand-alone training opportunity](https://github.com/carpentries/strategic-plan#goal-4-facilitate-the-creation-and-maintenance-of-relevant-high-quality-community-curated-curricula) for non-Carpentries audiences.

In addressing all of these goals, it is of primary importance that our curriculum remain up-to-date and optimized for ease of use. The next update to the Instructor Training curriculum will include a review of literature related to core content to ensure that our treatment of evidence-based practices is fully up-to-date. It will also address chronic problems with timing and Trainer uncertainty with content instruction (e.g. workshop website setup). Updates will be lead by Core Team members and curriculum Maintainers with support from the Trainer community.

**Comment by karenword** [comment]
We are in the midst of updates currently. We hope to have them mostly completed within Q2, and anticipate a substantial rollout period including community testing and feedback prior to merging in the main repository in Q3. Updates are currently taking place in a sandbox repository: https://github.com/data-lessons/instructor-training

**Comment by kariljordan** [comment]
@karenword can we close this now that the updates have been released?

**Comment by karenword** [comment]
The updates have not yet been released -- they are only in beta testing with the Trainer community. I will respond to feedback from these initial workshops, then initiate a substantial PR campaign within the Trainer community before merging into the main repo and completing the release. I will close this issue at that time.

**Comment by karenword** [comment]
Feedback has been addressed and (finally) merged within the data-lessons repository. Surveys regarding updates will go out to Trainers this week. Assuming no overwhelming signs of concern about the updates, we should be ready to return to the main repository by the end of October.

**Comment by karenword** [comment]
Updated curriculum was [released](https://github.com/carpentries/instructor-training/releases/tag/v2021.11.18-1) 17 Nov, 2021
