### ISSUE TITLE
Continue Plan and Pilot of Community Facilitators Program

### ISSUE THREAD

**Issue by kariljordan** [carpentries/strategic-plan#25]
**<ins>Context</ins>**
In 2019, Kari Jordan, Tracy Teal, Sher! Hurt and Serah Rono constituted a working group that discussed supporting community members through conflict. From our working group's deliberations, we saw the need to set up a task force that would issue recommendations for dealing with incidents that come up in spaces where our community members are but whose review and resolution fall outside the mandate of The Carpentries Code of Conduct (CoC) committee.([See task force charter](https://github.com/carpentries/task-forces/blob/master/2019/incidents-outside-cocc/2019-07-incidents-outside-cocc-charter.md). 

[One of the key recommendations from this Task Force was the institution of a Code of Conduct Facilitators Program](https://github.com/carpentries/task-forces/blob/master/2019/incidents-outside-cocc/2019-09-19-cocc-taskforce-summary-recommendations.md#recommendation-2-volunteer-code-of-conduct-facilitators) to serve as an added layer of support for our community before incidents are reported to the Code of Conduct Committee (CoCc). Details in the Code of Conduct Facilitators Program were first proposed by Malvika Sharan in Q1 2019. In summary, while maintaining the role of the CoCc as a CoC enforcement body, Code of Conduct Facilitators would actively monitor our online spaces and physical meetings and share potentially negative behaviours or otherwise certify that the community is functioning as expected. 

The Carpentries is keen to expand on the original mandate of Code of Conduct Facilitators in The Carpentries beyond support for others in situations of conflict, and hope to include elements of encouragement and positive facilitation that are necessary for the health and continuance of an established community like The Carpentries as part of the mandate of community facilitators in The Carpentries. This, we believe, will help Facilitators feel more fulfilled in this role, and open up pathways for them to build trust with community members, a necessary aspect of this role. 

**<ins>Phases of the Community Facilitators Program</ins>**
Planning a  Pilot for the Community Facilitators Program is the third of multiple phases toward the creation and launch of the Community Facilitators Program in The Carpentries. Other phases are: 

- Phase 1: https://github.com/carpentries/strategic-plan/issues/14
- Phase 2: https://github.com/carpentries/strategic-plan/issues/20
- Phase 4: https://github.com/carpentries/strategic-plan/issues/33

**<ins>Aims of the four-phase Community Facilitators Program</ins>**
- Develop a curriculum module to address recommendation 2 from Q3 2019’s Task Force work
- Train first cohort of Community Facilitators on Code of Conduct facilitation
- Pilot Code of Conduct facilitation
- Identify topics for additional modules for the Community Facilitators Program
- Invite community members to apply to be in the second cohort of the Community Facilitators Program
- Train second cohort of Community Facilitators
- Prepare second cohort of Community Facilitators for collaborative work in the first half of 2021
- Offboard first cohort of Community Facilitators

**<ins>Aims of the Community Facilitators Program</ins>**
- Change the existing Code of Conduct enforcement mechanism that The Carpentries has in place
- Redesign or replace The Carpentries Mentorship program
- Develop a curriculum and resources for local community building in The Carpentries
- Develop a framework for a communications committee

**<ins>Work that will constitute Plan Pilot of Community Facilitators Program (Phase 3 work)</ins>**
- [x] put out a call for applications so community members can register interest to take part in the first pilot phase
- [x] review community applications
- [x] short list and send out acceptance correspondence to community members for first Community Facilitators Program cohort.
- [x] Develop a post-training collaborative framework to guide trained Community Facilitators in creating resources to support The Carpentries community for a defined period of time after the training

**Comment by kariljordan** [comment]
@serahrono as this work is ongoing, I'd like to propose that we rename this issue **Community Facilitators Program** and add a comment to share next steps with the Code of Conduct Facilitators.

**Comment by serahkiburu** [comment]
In the first phase of the Community Facilitators Program, we 
- [launched and announced the program](https://carpentries.org/blog/2020/09/introducing-community-facilitators-program/) to our community, 
- [developed resources to onboard and support Feedback Facilitators](https://carpentries.github.io/community-facilitators-program/02-0-feedback-facilitation/index.html) in The Carpentries,
- [put out a call for applications](https://carpentries.org/blog/2020/09/apply-feedback-facilitators-cohort/), selected and [announced our first cohort of feedback facilitators](https://carpentries.org/blog/2020/09/introducing-community-facilitators-program/) , 
-  worked with feedback facilitators [to collect feedback over the last six months](https://github.com/carpentries/community-facilitators-program/projects/1) around
   - use of breakout rooms in online workshops
   - all things access and accessibility - challenges community members have faced over the last year and recommendations on alleviating those
   - more general feedback around learning and teaching using Carpentries lesson material and in Carpentries workshops

At the end of May 2021, our first cohort of Feedback Facilitators will be showcasing their work to our community.

**Comment by serahkiburu** [comment]
In the second phase of the Community Facilitators Program, 
- we have been drafting the Code of Conduct module to train and onboard community members interested in serving as a bridge between the Code of Conduct committee and the rest of the community. We hope to [publish the module here on GitHub](https://carpentries.github.io/community-facilitators-program/03-0-code-of-conduct-facilitation/index.html) and carry out our first Code of Conduct facilitators onboarding in Q2 2021.
- we will also be drafting the [Communications Facilitation module]((https://carpentries.github.io/community-facilitators-program/04-0-communications-facilitation/index.html)) and launching it later in 2021
- we also hope to work on the [Accessibility Facilitation module](https://carpentries.github.io/community-facilitators-program/07-0-accessibility-facilitation/index.html) as a collaborative effort between the Community Development Team and Instructor Training Team.
-

**Comment by acrall** [comment]
This program is being restructured to align with the Champions and Regional Coordinators programs. Blog post announcing this can be found [here](https://carpentries.org/blog/2021/10/announcing-community-development-program/).

**Comment by acrall** [comment]
Closing this issue because restructuring into Community Development Program
