### ISSUE TITLE
Pilot CarpentryConnect Kit in a Regional CarpentryConnect 

### ISSUE THREAD

**Issue by kariljordan** [carpentries/strategic-plan#26]
[Goal 1](https://github.com/carpentries/strategic-plan/blob/master/STRATEGIC-PLAN.md#goal-1-build-regional-and-local-capacity-to-empower-sustainable-communities) is to _**Build regional and local capacity to empower sustainable communities.**_ One of the objectives under goal 1 is:

Develop a kit of resources, templates, and documentation to help build local communities and enable them to run their own CarpentryConnect events so that they can share experiences and learn from one another locally, regionally, and globally.

This issue tracks progress for the development of the CarpentryConnect Planning Kit.

**Comment by serahrono** [comment]
Community members in The Nordics and East Coast US have requested that we revisit this in Q2 2021. @kariljordan I propose that we change the timeline label to Q2 2021.

**Comment by serahrono** [comment]
[We will also have CarpentryConnect South Africa running in September 2021](https://eventfund.codeforscience.org/announcing/), and can add a Q3 2021 label.

**Comment by elletjies** [comment]
Linking to Kari's blog post (Highlighting our strategic plan efforts to support local community building) - https://carpentries.org/blog/2021/07/Highlighting-our-strategic-plan-efforts-to-support-local-community-building/

"The main goal of CarpentryConnect South Africa is to build capacity for workshops through instructor training, and establish a network for this regional Carpentries community. We are attracting students, researchers, technologists, librarians, and others who find value in working with data and software in an effort to build and scale Carpentries activities in the region. The CarpentryConnect South Africa planning committee has put the CarpentryConnect Kit to good use as they organise this regional, virtual event, and we hope to inspire other regions to work collaboratively to advocate for our vision and values as well."

Here are other blog posts as well: 

https://carpentries.org/blog/2021/09/carpentryconnect/
https://carpentries.org/blog/2021/06/CarpentryConnectSouthAfrica/

**Comment by acrall** [comment]
Australia and New Zealand are also planning a regional CarpentryConnect event in November 2021. The CDT plans to develop a process for allowing community members to register their events so we can effectively promote through our channels and to also follow up with hosts of these events following their completion to get feedback.

**Comment by kariljordan** [comment]
There are currently no CarpentryConnects being planned for which the kit is being piloted. @elletjies has been updating the kit with lessons learned from the South African event. This issue is now complete.
