### ISSUE TITLE
Develop Roles and Responsibilities for Curriculum Advisors Program

### ISSUE THREAD

**Issue by kariljordan** [carpentries/strategic-plan#29]
[Goal 4](https://github.com/carpentries/strategic-plan#goal-4-facilitate-the-creation-and-maintenance-of-relevant-high-quality-community-curated-curricula) of our strategic plan is to "Facilitate the creation and maintenance of relevant, high-quality, Community-curated curricula.". One of the objectives under this goal is: 

- Develop a Community-led Curriculum Advisors program, including roles and responsibilities, regular cycles for recruitment/retirement, and communication pathways between Maintainers, Curriculum Advisors, and lesson program Advisory Councils.

The specific scope of work for this issue is to develop roles and responsibilities for the Curriculum Advisors program, which currently exists, but is largely inactive. 

**To Do**
- [x] Document roles and responsibilities for CAC members, including an organisational role. 
- [x] Update documentation of these [roles and responsibilities in The Carpentries Handbook](https://docs.carpentries.org/topic_folders/lesson_development/lesson_development_roles.html#curriculum-advisory-committee). 

**Background on the Curriculum Advisors program**

In our [Maintainer interviews and survey](https://datacarpentry.org/blog/2018/01/maintainer-report) conducted at the end of 2017, one lesson learned was that Maintainers did not feel comfortable introducing large-scale changes into their lessons and were concerned that they did not have the authority to do so. Maintainers signed on for their role with the understanding that they would be responsible for day-to-day maintenance and small improvements, but were often being asked by contributors to implement major overhauls to the curriculum (including introducing new tools or packages or completely changing the lesson narrative). This feedback enabled us to identify a missing layer of our lesson support structure, which will be filled by Curriculum Advisory Committees for each curriculum. 

The vision for Curriculum Advisors is to provide high-level oversight, vision, and leadership for a curriculum and guide large-scale updates. Unlike Maintainers, who are responsible for the day-to-day work of keeping lessons stable and teachable, Curriculum Advisors maintain a broader perspective on the state of the field and make strategic decisions about major changes to a lesson, for example, updating the technology being taught to take into account major advances in the field or changing the dataset used in the lessons to appeal to a broader group of learners. We currently have Curriculum Advisory Committees for [Data Carpentry Social Science, Geospatial, and Genomics lessons](https://datacarpentry.org/curriculum-advisors/), as well as [Software Carpentry overall](https://software-carpentry.org/curriculum-advisors/). [Library Carpentry has a similar governance body](https://librarycarpentry.org/advisory/), which was developed independently. 
 
A Curriculum Advisory Committee (CAC) is composed of 5-8 people with significant domain expertise who represent the breadth of the field that a curriculum is intended to reach. For example, the Data Carpentry Geospatial CAC includes researchers in ecology, limnology, environmental sciences, and sociology, along with university staff leading institutional GIS education efforts. Multiple career levels are represented, from PhD candidates at the end of their graduate work, to mid-late career professionals. At least one member of the CAC should be actively teaching in the field, so they can bring a practical perspective about what skills students and early-career researchers need. Curriculum Advisors commit to a minimum one-year term, but may serve multiple terms. A CAC should include members from multiple geographic regions and cultural and linguistic contexts to ensure that the curriculum meets the needs of our global community.
 
A Curriculum Advisory Committee meets virtually approximately twice a year to discuss and make decisions about proposed large-scale changes to the lessons within their curriculum. These proposals may be initiated by community members, including Maintainers, or by members of the CAC. The CAC communicates their recommendations back to the Lesson Maintainers and provides consultation and support to Maintainers in implementing proposed changes.
 
This model has been effective in guiding a major plotting system update prior to publication of our new Geospatial curriculum, and in modernizing the data and toolkit used in our Genomics curriculum.

Since being established in 2018, most of our Curriculum Advisory Committees have become inactive. There is a need for self-governance of these groups, to internally organise and facilitate meetings and communicate out action items and decisions.

**Comment by ErinBecker** [comment]
The Curriculum Team is in the process of planning a quarterly project to begin working on this item - to start in Q3 2021 (July - September).

**Comment by lexnederbragt** [comment]
This item should also be considered in light of the ongoing work in the Executive Council Program committee on [Lesson Program Governance](https://github.com/carpentries-ec/conversations_ec_ed/issues/103).

**Comment by ErinBecker** [comment]
[Roles and responsibilities](https://docs.carpentries.org/topic_folders/lesson_development/lesson_development_roles.html) for the CACs have been updated in the handbook, including formal roles for committee Chair and Secretary. The Maintainers community has also supported development of a [CAC Consultation Rubric](https://docs.carpentries.org/topic_folders/lesson_development/cac-consult-rubric.html) defining division of responsibilities between Maintainers and Curriculum Advisors. 

@kariljordan  - Although both of the tasks on this issue are complete, work is still ongoing to recruit and onboard the new CACs. Should this issue be closed or kept open to record next steps?

**Comment by kariljordan** [comment]
Thanks, @ErinBecker! You can close this issue and make updates to #45 which is about solidifying community leadership roles.
