### ISSUE TITLE
Carry out first pilot of Community Facilitators Program

### ISSUE THREAD

**Issue by kariljordan** [carpentries/strategic-plan#33]
**<ins>Context</ins>**
In 2019, Kari Jordan, Tracy Teal, Sher! Hurt and Serah Rono constituted a working group that discussed supporting community members through conflict. From our working group's deliberations, we saw the need to set up a task force that would issue recommendations for dealing with incidents that come up in spaces where our community members are but whose review and resolution fall outside the mandate of The Carpentries Code of Conduct (CoC) committee.([See task force charter](https://github.com/carpentries/task-forces/blob/master/2019/incidents-outside-cocc/2019-07-incidents-outside-cocc-charter.md). 

[One of the key recommendations from this Task Force was the institution of a Code of Conduct Facilitators Program](https://github.com/carpentries/task-forces/blob/master/2019/incidents-outside-cocc/2019-09-19-cocc-taskforce-summary-recommendations.md#recommendation-2-volunteer-code-of-conduct-facilitators) to serve as an added layer of support for our community before incidents are reported to the Code of Conduct Committee (CoCc). Details in the Code of Conduct Facilitators Program were first proposed by Malvika Sharan in Q1 2019. In summary, while maintaining the role of the CoCc as a CoC enforcement body, Code of Conduct Facilitators would actively monitor our online spaces and physical meetings and share potentially negative behaviours or otherwise certify that the community is functioning as expected. 

The Carpentries is keen to expand on the original mandate of Code of Conduct Facilitators in The Carpentries beyond support for others in situations of conflict, and hope to include elements of encouragement and positive facilitation that are necessary for the health and continuance of an established community like The Carpentries as part of the mandate of community facilitators in The Carpentries. This, we believe, will help Facilitators feel more fulfilled in this role, and open up pathways for them to build trust with community members, a necessary aspect of this role. 

**<ins>Phases of the Community Facilitators Program</ins>**
Carrying out first pilot of Community Facilitators Program is the fourth of multiple phases toward the creation and launch of the Community Facilitators Program in The Carpentries. Other phases are: 

- Phase 1: https://github.com/carpentries/strategic-plan/issues/14
- Phase 2: https://github.com/carpentries/strategic-plan/issues/20
- Phase 3: https://github.com/carpentries/strategic-plan/issues/25

**<ins>Aims of the four-phase Community Facilitators Program</ins>**
- Develop a curriculum module to address recommendation 2 from Q3 2019’s Task Force work
- Train first cohort of Community Facilitators on Code of Conduct facilitation
- Pilot Code of Conduct facilitation
- Identify topics for additional modules for the Community Facilitators Program
- Invite community members to apply to be in the second cohort of the Community Facilitators Program
- Train second cohort of Community Facilitators
- Prepare second cohort of Community Facilitators for collaborative work in the first half of 2021
- Offboard first cohort of Community Facilitators

**<ins>Aims of the Community Facilitators Program</ins>**
- Change the existing Code of Conduct enforcement mechanism that The Carpentries has in place
- Redesign or replace The Carpentries Mentorship program
- Develop a curriculum and resources for local community building in The Carpentries
- Develop a framework for a communications committee

**<ins>Resources that will constitute Phase 4 work</ins>** 
- [x] Train and support first cohort of community facilitators in The Carpentries
- [x] Determine aspects of the fourth phase to communicate about at different stages of the work
- [x] Review the existing post-training collaborative framework used to guide trained Community 
Facilitators in creating resources to support The Carpentries community for a defined period of time after the training, and update it if need be
- [x] Identify additional modules to develop for the Community Facilitators Program
- [x] Retrospective and assessment of Phase 4: Collect feedback from first cohort of Community Facilitators and use it to update training resources for future cohorts of the program

**Comment by serahrono** [comment]
This is going really well, had a check-in with individual facilitators this week, and there is interest in extending their feedback facilitation fellowship for a year, in place of the six months originally proposed. This is a great idea, and we will do that. Their ongoing feedback collection and facilitation work is being tracked [in the Community Facilitators repository](https://github.com/carpentries/community-facilitators-program/issues), and I propose marking this pilot task complete.

**Comment by kariljordan** [comment]
Amazing! Thanks so much.
