### ISSUE TITLE
Launch bonus IT module: Introduction to online training practices for current Instructors

### ISSUE THREAD

**Issue by kariljordan** [carpentries/strategic-plan#35]
[Goal 3](https://github.com/carpentries/strategic-plan#goal-3-provide-opportunities-for-growth-and-professional-development-of-our-volunteers-and-core-team) of The Carpentries Strategic Plan reads: **Provide opportunities for growth and professional development of our volunteers and Core Team.**  Among the objectives is:

- Develop Instructor Training refresher modules to keep Trainers current in educational and Carpentries-specific practices, and provide opportunities for continued learning.

In response to the present demand for online training, we are currently developing a continuing education 'bonus module' that will support certified Instructors in preparing to teach online. This module will include technical instruction (e.g. zoom hosting & cloud instance setup) as well as review of core Carpentries teaching practices as they apply in an online context. This module will be drafted by Core Team members and finalized/maintained in collaboration with the Trainer community.

To do:
- [x] Draft module
- [x] Engage Trainer community in iterative development
- [x] Develop administrative processes to offer module to Instructor community & track participation
- [x] Recruit Trainers to teach module
- [x] Work with Trainer community/leadership to recognize instructional effort towards bonus modules as partial fulfillment of the Trainer Agreement

**Comment by karenword** [comment]
All 'to do' items are complete, but I am leaving this item open because we do hope to continue to advance work on the bonus modules in 2021, adding one or more additional topics.

**Comment by kariljordan** [comment]
@karenword can we open a separate issue to track the work on new bonus modules and close this one?

**Comment by karenword** [comment]
I will close this issue. It may be most efficient to track the next Bonus Module in #50 since it is directly relevant there. Let me know if you think it would be better to open a new issue instead.
