### ISSUE TITLE
Lesson Program Governance Structure

### ISSUE THREAD

**Issue by kariljordan** [carpentries/strategic-plan#4]
[Goal 5](https://github.com/carpentries/strategic-plan/blob/master/STRATEGIC-PLAN.md#goal-5-strengthen-organisational-structure-and-capacity-to-be-strategic-and-responsive) in the Carpentries strategic plan is to _**Strengthen organisational structure and capacity to be strategic and responsive.**_ Under this goal is the following objective:

Create an organised and engaged Lesson Program governance structure and strengthen Lesson Programs’ oversight of their Programs.

This issue tracks progress made towards developing a Lesson Program governance structure.

**Comment by lexnederbragt** [comment]
This item should also be considered in light of the ongoing work in the Executive Council Program committee on [Lesson Program Governance](https://github.com/carpentries-ec/conversations_ec_ed/issues/103).

**Comment by kariljordan** [comment]
@lexnederbragt after the December EC meeting can you update this issue?

**Comment by lexnederbragt** [comment]
At the 2021-12-21 Executive Council meeting, the new Lesson Program Governance policy was approved. It was implemented as a set of changes to the handbook in https://github.com/carpentries/docs.carpentries.org/pull/809.

**Comment by kariljordan** [comment]
Reopening this issue per the comment below from @tobyhodges:

"I don't think this is complete. The EC approved the Lesson Program Governance policy, and added it to the Handbook, but we have not yet established that Lesson Program Governance. The Curriculum Team has this planned for the second half of 2022."

**Comment by tobyhodges** [comment]
As of today, 2023-04-21, Lesson Program Governance Committees have been established for Data Carpentry, Library Carpentry, and Software Carpentry.
Onboarding was completed this week, with each committee having two officers: a Chair and Secretary (* SWC has two Co-chairs).
Repositories have been created for each new committee or, in the case of LC, modified from an existing repo:

- https://github.com/datacarpentry/governance
- https://github.com/LibraryCarpentry/governance
- https://github.com/swcarpentry/governance

At time of writing, each of those repositories has a pull request pending to add a committee charter document. Committees will begin scheduling their first meetings in the coming weeks.

Although there is still more work to do to support the committees, such as the publication of a blog post welcoming the new committees and of the Lesson Program Governor Handbook (currently in review), I am going to close this issue.
