### ISSUE TITLE
Trainers Leadership Governance

### ISSUE THREAD

**Issue by kariljordan** [carpentries/strategic-plan#44]
[GOAL 1](https://github.com/carpentries/strategic-plan/blob/master/STRATEGIC-PLAN.md#goal-1-build-regional-and-local-capacity-to-empower-sustainable-communities) of the Carpentries strategic plan is to **_build regional and local capacity to empower sustainable communities._** Our Instructor Training program is a vital component of local capacity building. Two of the objectives under goal 1 are:
- Create and implement a program for developing Local Leadership, including mentorship for new Leaders, communication channels for connecting Local Leaders, and explicit training in our values, Code of Conduct, and Equity, Inclusion, and Accessibility.
- Develop a plan to work with local and regional communities to ensure they are supported appropriately by Regional Coordinators, Trainers, and other community roles that work in a location-specific manner.

[Goal 3](https://github.com/carpentries/strategic-plan/blob/master/STRATEGIC-PLAN.md#goal-3-provide-opportunities-for-growth-and-professional-development-of-our-volunteers-and-core-team) is to _**Provide opportunities for growth and professional development of our volunteers and Core Team.**_ One of the objectives under goal 3 is:
- Solidify current committee leadership roles, responsibilities, and governing documents

The Instructor Trainer community elected a [Trainers Leadership Group](https://carpentries.org/blog/2021/03/announcing-new-Trainers-leadership-members/) and ratified a preliminary governance structure for this Carpentries sub-community. This panel and its documentation remains provisional, pending creation of guidelines and an approval process for sub-community governance by The Carpentries Executive Council. In the interim, they will proceed to flesh out procedural plans and will engage with The Carpentries Core Team to represent the interests of the Trainer community on policies and plans that pertain to Instructor Training.

**This issue will track progress and updates on the Trainers Leadership Group.**

**Comment by karenword** [comment]
This group has been preparing to deliver its first annual report to the Executive Council. They are currently supporting an overhaul of the Trainer Agreement and after that will be focused on the second annual election.

**Comment by karenword** [comment]
This group was approved by the Executive Council on May 9, 2022.
