### ISSUE TITLE
Solidifying Community Leadership Roles

### ISSUE THREAD

**Issue by kariljordan** [carpentries/strategic-plan#45]
[Goal 3](https://github.com/carpentries/strategic-plan/blob/master/STRATEGIC-PLAN.md#goal-3-provide-opportunities-for-growth-and-professional-development-of-our-volunteers-and-core-team) is to _**Provide opportunities for growth and professional development of our volunteers and Core Team.**_ One of the objectives under goal 3 is:
- Solidify current committee leadership roles, responsibilities, and governing documents

The Executive Council amended the [handbook](https://docs.carpentries.org/topic_folders/governance/committee-policy.html) to include the Carpentries [Committee Policy](https://docs.carpentries.org/topic_folders/governance/committee-policy.html) and [Task Force Policy](https://docs.carpentries.org/topic_folders/governance/task-force-policy.html).

**Comment by kariljordan** [comment]
After approving this policy, the EC realised that they should have involved current Committees and Task Forces (and the wider Carpentries community) while formulating these policies. They apologised for this omission and now have thus a two-fold request:
1) committees and task forces should begin preparations to adhere to the policy
2) please give the EC feedback on things the Committees and Task Forces see as problematic with the Policy as currently stated. GitHub Issue: https://github.com/carpentries/docs.carpentries.org/issues/700

After receiving feedback, they will discuss adjusting the policies where necessary.

**Deadlines:**

- feedback on the Policy: March 1st
- submission of the public documentation: to be determined, depending on the feedback we receive

**Comment by kariljordan** [comment]
Related: https://github.com/carpentries/docs.carpentries.org/issues/700

**Comment by kariljordan** [comment]
@lexnederbragt can you update this issue per the EC's stance on approving committees/task forces?

**Comment by kariljordan** [comment]
The Executive Council worked extensively to clarify its roles and responsibilities as it relates to the governance of the organization. Learn more in their [recently published blog post](https://carpentries.org/blog/2021/07/carpentries-governance/). In short, it is no longer a requirement for committees/task forces to be *approved* by the EC.

**Comment by kariljordan** [comment]
The EC’s decision-making transparency led to a change in the [Committee Policy (in Handbook)](https://docs.carpentries.org/topic_folders/governance/committee-policy.html) where the EC no longer needs to approve all committees. The handbook will be updated to reflect this information. The EC received feedback about the committee and task force policy in general, and that feedback still needs to be addressed: carpentries/docs.carpentries.org#700

The Carpentries Team Leads are encouraged to work with community members to formalize community roles, however, there is no requirement for the EC to approve committees or task forces. I will leave this issue open until we have confirmed that all community leadership has roles, responsibilities, and governing documents.

**Comment by ErinBecker** [comment]
I am currently working to [establish and formalize Curriculum Advisory Committees](https://carpentries.org/blog/2021/08/reactivating-curriculum-advisory-committees/) for each of our official curricula. Recruitment is underway and will wrap up the end of October. New committee members will be onboarded in November. Onboarding is being developed and will be added to [Handbook](https://docs.carpentries.org/topic_folders/lesson_development/lesson_development_roles.html#curriculum-advisory-committees) when available.

**Comment by acrall** [comment]
I am working with @sheraaronhurt to transition the Instructor Development Committee (IDC) from the Community Development Team (CDT)nto the Workshop Admin Team (WAT). Current IDC members will be offboarded at the end of October 2021 and a new annual onboarding process will be developed and initiated in January 2022. The plan is to recruit and select new members to be onboarded in February 2022. Starting November 2021, the CDT will manage the scheduling of community discussions, and this will no longer be the responsibility of the IDC.

**Comment by sheraaronhurt** [comment]
The Roles & Responsibilities have been updated for the IDC in [the handbook](https://docs.carpentries.org/topic_folders/instructor_development/instructor_development_committee.html#instructor-development-committee-roles) as of January 1, 2022.

**Comment by kariljordan** [comment]
Thanks so much @sheraaronhurt! Once [this PR](https://github.com/carpentries/carpentries.org/pull/1286) is approved and merged we will have documentation for all of our active community leadership and this issue will be closed.

**Comment by kariljordan** [comment]
Closing this issue as we now have governing documents for all active committees and task forces (see [this PR](https://github.com/carpentries/carpentries.org/pull/1286)).
