### ISSUE TITLE
Instructor Training Bonus Module on Equity, Inclusion, and Accessibility

### ISSUE THREAD

**Issue by kariljordan** [carpentries/strategic-plan#50]
[Goal 3](https://github.com/carpentries/strategic-plan/blob/main/STRATEGIC-PLAN.md#goal-3-provide-opportunities-for-growth-and-professional-development-of-our-volunteers-and-core-team) of the Carpentries Strategic Plan is to _**Provide opportunities for growth and professional development of our volunteers and Core Team.**_ One of the objectives under this goal is:
- Develop Instructor Training refresher modules to keep Trainers current in educational and Carpentries-specific practices, and provide opportunities for continued learning.

This issue tracks progress towards an Instructor Training bonus module on Equity, Inclusion, and Accessibility.

**Comment by karenword** [comment]
We plan to begin work on an EIA [bonus module](https://github.com/carpentries/strategic-plan/issues/35) in Q3 2021.

**Comment by karenword** [comment]
The timeline for the bonus module has been extended substantially to accommodate support from the Equity Council established by the Sloan grant. However, the Equity Council has met once and has provided feedback on the new [episode on Equity, Inclusion, and Accessibility](https://data-lessons.github.io/instructor-training/09-eia/index.html) in the updated curriculum. This feedback has been addressed at a basic level and will carry forward into the development of the bonus module. 

The EIA episode includes new content on Universal Design for Learning as well as enhanced focus on Carpentries Core Values, the concept of equity, and ways to promote inclusion using Carpentries teaching practices.

**Comment by kariljordan** [comment]
@karenword can you provide an update on this issue?

**Comment by kariljordan** [comment]
I am closing this and will reopen next year when we are actively working on the bonus module. The Equity Council did some brainstorming to work on learning objectives for a continuing education module, however we are not actively working on content for this module, so we will reopen this issue when the work is active.
