### ISSUE TITLE
Updating The Carpentries Membership Model & Membership Processing Workflow

### ISSUE THREAD

**Issue by kariljordan** [carpentries/strategic-plan#52]
[Goal 5](https://github.com/carpentries/strategic-plan/blob/master/STRATEGIC-PLAN.md#goal-5-strengthen-organisational-structure-and-capacity-to-be-strategic-and-responsive) in the Carpentries strategic plan is to _**Strengthen organisational structure and capacity to be strategic and responsive.**_ Under this goal is the following objective:
- Update the model for Carpentries Membership to match the needs of different types of communities, support the development of local capacity for training, improve operational efficiency, and be a significant part of the revenue model that provides adequate funding to sustain Carpentries activities.

This issue will track our progress for:

- [x] Updating The Carpentries membership model.
- [x] Updating The Carpentries membership processing workflow.

**Comment by kariljordan** [comment]
Copied over from #7:

Progress  was made Feb 17 - March 31, 2020 in researching how to develop membership models through libraries.
**California Consortia Pilot - Ariel Deardorff (UCSF) and Catherine Nancarrow (CDL)**
- Established scope of work and timeline
- Conducted check-In Meetings
- Scanning the landscape and researching options for consortia type business models
- Analyze UC Membership Data
- Establishing outreach to Community Colleges and California State Universities.
- Establishing contacts between my connections and UCSF and CDL
- Created a discussion document to determine the needs, priorities and a timeline of the Membership program

**Establishing a framework for a Membership Database**
- Analysis of what data is needed and data that is not collected by the organization that we would need

**Provide research on Gift/Sponsorship Policies - purpose is for the Carpentries to establish a policy on who they will accept Memberships from i.e. corporations, institutions, etc.**
- Best practices with other nonprofits
- Links to why it is important to set up a policy and examples of policies

**Comment by Al-Obayuwana** [comment]
Working on editing and revising the draft [workflow ](https://docs.google.com/document/d/1F8qtagtXk-WtiIgpAtBY5t6Hg2rE5LClaEfee26z70w/edit#heading=h.u0gidtoxc0ez)for membership processing in Q3. We are also working on a project plan for the membership pricing structure, this is also a Q3 project.

**Comment by Al-Obayuwana** [comment]
Workflow has been updated, final draft and new templates are being created. The new pricing structure should be approved today barring any setbacks.

**Comment by ErinBecker** [comment]
The [new pricing model](https://carpentries.org/membership/) was [announced](https://carpentries.org/blog/2021/11/membership-pricing-update/) in November 2021 and [went into effect](https://carpentries.org/blog/2022/01/new-prices-in-effect/) in January. Our [membership workflow](https://docs.google.com/document/d/1F8qtagtXk-WtiIgpAtBY5t6Hg2rE5LClaEfee26z70w/edit#heading=h.o8un9iv0q603) has been updated, and our [membership agreement](https://docs.google.com/document/d/1ZcvCSdfgZZo3QInxAm7cJpF6bZGTxSyVSsXDHszbR80/edit) and [MOU templates](https://docs.google.com/document/d/1So1owMKJ2FFYDmBrOwjeAVtVofDIDPIX27z8Fm8xaAs/edit) have been greatly simplified.
