### ISSUE TITLE
Workflow for Responding to Accessibility Information in Workshops

### ISSUE THREAD

**Issue by kariljordan** [carpentries/strategic-plan#57]
[Goal 2](https://github.com/carpentries/strategic-plan/blob/master/STRATEGIC-PLAN.md#goal-2-intentionally-incorporate-equity-inclusion-and-accessibility-to-support-a-diverse-community) of the Carpentries Strategic Plan is to Intentionally incorporate equity, inclusion, and accessibility to support a diverse community. One of the objectives under this goal is to: **_Develop a workflow for responding to accessibility information and feedback to improve accommodations for Instructors and Learners._**

This issue tracks progress for developing a workflow to respond to accessibility information we receive to improve accommodations for Instructors and Learners.

**Comment by sheraaronhurt** [comment]
This has been added to the [Workshop Admin Team Roadmap](https://app.asana.com/0/1202691289972063/1202691289972274). @brynnelliott will be leading these efforts. Work will begin on this is Q1 2023.

**Comment by sheraaronhurt** [comment]
@brynnelliott is preparing to start working on this in Q1 2023. The WAT met this week and agreed upon the goals for Q1 and this was one of them.

**Comment by sheraaronhurt** [comment]
The Accessibility Manager has developed an [Accessibility Accommodation Form](https://carpentries.typeform.com/to/B2OSYaD0) to be shared in Carpentries Events
Developing material to share with Instructors regarding the importance of accessibility needs
Released [Accessibility Statement](https://carpentries.org/blog/2023/03/accessibility-statement-and-accommodation-form/)
The Accessibility Manager is developing a DEI statement to be added to our website

**Comment by sheraaronhurt** [comment]
Completed. See links above.

**Comment by sheraaronhurt** [comment]
Completed. See links above.
